apiVersion: 1

datasources:
  - name: Postgres
    uid: talumboncompany
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: energy
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false