{
 "title": "Energy Overview",
 "time": { "from": "now-30y", "to": "now" },
 "panels": [
  {
   "title": "Total Primary Energy Production/Cosumption",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts, $__interval),\n  description AS \"metric\",\n  avg(value) AS \"value\"\nFROM primary_energy_production \nWHERE\n  $__timeFilter(ts)\nAND  description IN ('Total Fossil Fuels Production', 'Total Renewable Energy Production')\nGROUP BY 1,2\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts, $__interval),\n  description AS \"metric\",\n  avg(value) AS \"value\"\nFROM primary_energy_consumption\nWHERE\n  $__timeFilter(ts)\nAND  description IN ('Total Renewable Energy Consumption', 'Total Fossil Fuels Consumption')\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Primary Energy Production",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts, $__interval),\n  description AS \"metric\",\n  avg(value) AS \"value\"\nFROM primary_energy_production \nWHERE\n  $__timeFilter(ts)\n  AND  description NOT IN ('Total Primary Energy Production', 'Total Fossil Fuels Production', 'Total Renewable Energy Production')\n\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Primary Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts, $__interval),\n  description AS \"metric\",\n  avg(value) AS \"value\"\nFROM primary_energy_consumption\nWHERE\n  $__timeFilter(ts)\n AND  description NOT IN ('Total Renewable Energy Consumption', 'Total Fossil Fuels Consumption')\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Coal Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\",\nvalue AS \"Coal Consumption\"\nFROM primary_energy_consumption\nWHERE description='Coal Consumption'"
    },
    {
     "rawSql": "SELECT ts as \"time\",\nvalue AS \"Coal Production\"\nFROM primary_energy_production\nWHERE description='Coal Production'"
    }
   ]
  }
 ]
}