{
 "title": "Energy Overview",
 "time": { "from": "now-30y", "to": "now" },
 "panels": [
  {
   "title": "Overview Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "QBtu" } },
   "targets": [
    {
     "rawSql": "(SELECT ts as \"time\",\ndescription,\nvalue as \"QBtu\"\nFROM primary_energy_consumption\nWHERE description IN ('Total Primary Energy Consumption', 'Total Fossil Fuels Consumption', 'Total Renewable Energy Consumption')\nAND ts BETWEEN $__timeFrom()  AND $__timeTo() \n)\n\nUNION\n\n(SELECT ts as \"time\",\ndescription,\nvalue as \"QBtu\"\nFROM primary_energy_production\nWHERE description IN ('Total Primary Energy Production', 'Total Fossil Fuels Production', 'Total Renewable Energy Production')\nAND ts BETWEEN $__timeFrom()  AND $__timeTo() \n)\n\n\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Primary Energy Production",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "QBtu" } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\",\ndescription,\nvalue as \"QBtu\"\nFROM primary_energy_production\nWHERE description NOT IN ('Total Primary Energy Production', 'Total Fossil Fuels Production', 'Total Renewable Energy Production')\nAND ts BETWEEN $__timeFrom()  AND $__timeTo() \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Primary Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "QBtu" } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\",\ndescription,\nvalue as \"QBtu\"\nFROM primary_energy_consumption\nWHERE description NOT IN ('Total Primary Energy Consumption','Total Fossil Fuels Consumption', 'Total Renewable Energy Consumption')\nAND ts BETWEEN $__timeFrom()  AND $__timeTo() \nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Coal Production/Consumption",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "QBtu" } },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\",\ndescription, \nvalue AS \"QBtu\"\nFROM primary_energy_consumption\nWHERE description NOT IN ('Total Fossil Fuels Consumption', 'Total Renewable Energy Consumption', 'Total Primary Energy Consumption') AND ts BETWEEN $__timeFrom()  AND $__timeTo() \nUNION\n\nSELECT ts as \"time\",\ndescription, \nvalue AS \"QBtu\"\nFROM primary_energy_production\nWHERE description NOT IN ('Total Fossil Fuels Production', 'Total Renewable Energy Production', 'Total Primary Energy Production') AND ts BETWEEN $__timeFrom()  AND $__timeTo() \n\nORDER BY \"time\""
    }
   ]
  }
 ]
}